plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.17-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.0.15.RELEASE'
	id "com.thinkimi.gradle.MybatisGenerator" version "2.1.2"
	id 'groovy'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '11'
}

sourceSets {
	main {
		java.srcDirs = ['src/main/java']
		resources.srcDirs = ['src/main/resources']
	}
	test {
//		java.srcDirs = ['src/test/java']
		groovy.srcDirs = ['src/test/groovy']
		resources.srcDirs = ['src/test/resources']
	}
}


configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.3.1'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:2.3.1'
	runtimeOnly 'com.mysql:mysql-connector-j'
	// Spockフレームワーク
	testImplementation 'org.spockframework:spock-core:2.4-M1-groovy-3.0'
	testImplementation 'org.spockframework:spock-spring:2.4-M1-groovy-3.0'
	// Spring Bootテスト (JUnit 4サポートを除外)
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	// Groovyライブラリ
	implementation 'org.codehaus.groovy:groovy'

	testImplementation 'org.codehaus.groovy:groovy-all:3.0.17' // 必要に応じてGroovyのバージョンを指定
}

tasks.named('test') {
	useJUnitPlatform()
}